version: '3.8'

services:
#  postgres:
#    container_name: postgres
#    image: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 2004
#      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres
#    restart: unless-stopped
#
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "80:80"
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    networks:
#      - postgres
#    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

#volumes:
#  postgres:
#  pgadmin:
#
#networks:
#  postgres:
#    driver: bridge