spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://localhost:5433/customer
    username: root
    password: Lalitesh@2004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

  main:
    allow-bean-definition-overriding: true
server:
  port: 2001

eureka:
  instance:
    hostname: localhost
    appname: customer
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
