spring:
  application:
    name: fraud

  datasource:
    url: jdbc:mysql://localhost:5433/fraud
    username: root
    password: Lalitesh@2004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 2002

eureka:
  instance:
    appname: fraud
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    fetch-registry: true
    register-with-eureka: true
